<?php
include "admin.php";
session_start();
$qry = getAdminInformation($_SESSION['name']);

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$qry = getAdminInformation($name);
$adminInfo = mysqli_fetch_assoc($qry);
$name = $adminInfo['name'];
$fname = $adminInfo['fname'];
$lname = $adminInfo['lname'];
$email = $adminInfo['email'];
$contact = $adminInfo['contact'];

echo '<!--';
echo '=========================================================';
echo '* Paper Dashboard 2 - v2.0.1';
echo '=========================================================';
echo '';
echo '* Product Page: https://www.creative-tim.com/product/paper-dashboard-2';
echo '* Copyright 2020 Creative Tim (https://www.creative-tim.com)';
echo '';
echo 'Coded by www.creative-tim.com';
echo '';
echo '=========================================================';
echo '';
echo '* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.';
echo '-->';
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">';
echo '<link rel="icon" type="image/png" href="../assets/img/fox.jpg">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />';
echo '<title>';
echo 'Profile';
echo '</title>';
echo '<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no" name="viewport" />';
echo '<!--     Fonts and icons     -->';
echo '<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />';
echo '<link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">';
echo '<!-- CSS Files -->';
echo '<link href="../assets/css/bootstrap.min.css" rel="stylesheet" />';
echo '<link href="../assets/css/paper-dashboard.css?v=2.0.1" rel="stylesheet" />';
echo '<link href="../assets/demo/demo.css" rel="stylesheet" />';
echo '</head>';
echo '';
echo '<body class="">';
echo '<div class="wrapper ">';
echo '<div class="sidebar" data-color="white" data-active-color="danger">';
echo '<div class="logo">';
echo '<a href="../../../2114_pixie/index.html" class="simple-text logo-mini">';
echo '<div class="logo-image-small">';
echo '<img src="../assets/img/logo-small.png">';
echo '</div>';
echo '<!-- <p>CT</p> -->';
echo '</a>';
echo '<a href="../../../2114_pixie/index.html" class="simple-text logo-normal">';
echo 'Zootopika';
echo '<!-- <div class="logo-image-big">';
echo '<img src="../assets/img/logo-big.png">';
echo '</div> -->';
echo '</a>';
echo '</div>';
echo '<div class="sidebar-wrapper">';
echo '<ul class="nav">';
echo '<li>';
echo '<a href="./dashboard.html">';
echo '<i class="nc-icon nc-bank"></i>';
echo '<p>Dashboard</p>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="./map.html">';
echo '<i class="nc-icon nc-pin-3"></i>';
echo '<p>Maps</p>';
echo '</a>';
echo '</li>';
echo '<li class="active ">';
echo '<a href="./user.html">';
echo '<i class="nc-icon nc-single-02"></i>';
echo '<p>User Profile</p>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="./tables.html">';
echo '<i class="nc-icon nc-tile-56"></i>';
echo '<p>Table List</p>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="./tables.html">';
echo '<i class="nc-icon nc-user-run"></i>';
echo '<p>Logout</p>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="main-panel">';
echo '<!-- Navbar -->';
echo '<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">';
echo '<div class="container-fluid">';
echo '<div class="navbar-wrapper">';
echo '<div class="navbar-toggle">';
echo '<button type="button" class="navbar-toggler">';
echo '<span class="navbar-toggler-bar bar1"></span>';
echo '<span class="navbar-toggler-bar bar2"></span>';
echo '<span class="navbar-toggler-bar bar3"></span>';
echo '</button>';
echo '</div>';
echo '<a class="navbar-brand" href="javascript:;">Profile</a>';
echo '</div>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-bar navbar-kebab"></span>';
echo '<span class="navbar-toggler-bar navbar-kebab"></span>';
echo '<span class="navbar-toggler-bar navbar-kebab"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse justify-content-end" id="navigation">';
echo '<form>';
echo '<div class="input-group no-border">';
echo '<input type="text" value="" class="form-control" placeholder="Search...">';
echo '<div class="input-group-append">';
echo '<div class="input-group-text">';
echo '<i class="nc-icon nc-zoom-split"></i>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '<ul class="navbar-nav">';
echo '<li class="nav-item">';
echo '<a class="nav-link btn-magnify" href="javascript:;">';
echo '<i class="nc-icon nc-layout-11"></i>';
echo '<p>';
echo '<span class="d-lg-none d-md-block">Stats</span>';
echo '</p>';
echo '</a>';
echo '</li>';
echo '<li class="nav-item btn-rotate dropdown">';
echo '<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
echo '<i class="nc-icon nc-bell-55"></i>';
echo '<p>';
echo '<span class="d-lg-none d-md-block">Some Actions</span>';
echo '</p>';
echo '</a>';
echo '<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">';
echo '<a class="dropdown-item" href="#">Action</a>';
echo '<a class="dropdown-item" href="#">Another action</a>';
echo '<a class="dropdown-item" href="#">Something else here</a>';
echo '</div>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link btn-rotate" href="javascript:;">';
echo '<i class="nc-icon nc-settings-gear-65"></i>';
echo '<p>';
echo '<span class="d-lg-none d-md-block">Account</span>';
echo '</p>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '<!-- End Navbar -->';
echo '<div class="content">';
echo '<div class="row">';
echo '<div class="col-md-4">';
echo '<div class="card card-user">';
echo '<div class="image">';
echo '<img src="../assets/img/damir-bosnjak.jpg" alt="...">';
echo '</div>';
echo '<div class="card-body">';
echo '<div class="author">';
echo '<a href="#">';
echo '<img class="avatar border-gray" src="../assets/img/mike.jpg" alt="...">';
echo '<h5 class="title">'.$name.'</h5>';
echo '</a>';
echo '<p class="description">';
echo '@chetfaker';
echo '</p>';
echo '</div>';
echo '<p class="description text-center">';
echo '"I like the way you work it <br>';
echo 'No diggity <br>';
echo 'I wanna bag it up"';
echo '</p>';
echo '</div>';
echo '<div class="card-footer">';
echo '<div class="button-container">';
echo '<div class="row">';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="card">';
echo '<div class="card-header">';
echo '<h4 class="card-title">Team Members</h4>';
echo '</div>';
echo '<div class="card-body">';
echo '<ul class="list-unstyled team-members">';
echo '<li>';
echo '<div class="row">';
echo '<div class="col-md-2 col-2">';
echo '<div class="avatar">';
echo '<img src="../assets/img/faces/ayo-ogunseinde-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">';
echo '</div>';
echo '</div>';
echo '<div class="col-md-7 col-7">';
echo 'DJ Khaled';
echo '<br />';
echo '<span class="text-muted"><small>Offline</small></span>';
echo '</div>';
echo '<div class="col-md-3 col-3 text-right">';
echo '<btn class="btn btn-sm btn-outline-success btn-round btn-icon"><i class="fa fa-envelope"></i></btn>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="row">';
echo '<div class="col-md-2 col-2">';
echo '<div class="avatar">';
echo '<img src="../assets/img/faces/joe-gardner-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">';
echo '</div>';
echo '</div>';
echo '<div class="col-md-7 col-7">';
echo 'Creative Tim';
echo '<br />';
echo '<span class="text-success"><small>Available</small></span>';
echo '</div>';
echo '<div class="col-md-3 col-3 text-right">';
echo '<btn class="btn btn-sm btn-outline-success btn-round btn-icon"><i class="fa fa-envelope"></i></btn>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="row">';
echo '<div class="col-md-2 col-2">';
echo '<div class="avatar">';
echo '<img src="../assets/img/faces/clem-onojeghuo-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">';
echo '</div>';
echo '</div>';
echo '<div class="col-ms-7 col-7">';
echo 'Flume';
echo '<br />';
echo '<span class="text-danger"><small>Busy</small></span>';
echo '</div>';
echo '<div class="col-md-3 col-3 text-right">';
echo '<btn class="btn btn-sm btn-outline-success btn-round btn-icon"><i class="fa fa-envelope"></i></btn>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-8">';
echo '<div class="card card-user">';
echo '<div class="card-header">';
echo '<h5 class="card-title">Edit Profile</h5>';
echo '</div>';
echo '<div class="card-body">';


echo '<form action="processAdmin.php" method = "POST">';
echo '<div class="row">';
echo '<div class="col-md-4 pr-1">';
echo '<div class="form-group">';
echo '<label>Username (disabled)</label>';
echo "<input type='text' class='form-control' disabled='' placeholder='Username' name='name' value='$name'>";
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 px-1">';
echo '<div class="form-group">';
echo '<label>Contact Number</label>';
echo "<input type='text' class='form-control' placeholder='Contact' name='contact' value='$contact'>";
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 pl-1">';
echo '<div class="form-group">';
echo '<label for="exampleInputEmail1">Email address</label>';
echo "<input type='email' class='form-control' placeholder='Email' name='email' value='$email'>";
echo '</div>';
echo '</div>';
echo '</div>';
echo '<br>';
echo '<div class="row">';
echo '<div class="col-md-6 pr-1">';
echo '<div class="form-group">';
echo '<label>First Name</label>';
echo "<input type='text' class='form-control' placeholder='First Name' name='name' value='$fname'>";
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 pl-1">';
echo '<div class="form-group">';
echo '<label>Last Name</label>';
echo "<input type='text' class='form-control' placeholder='Last Name' name='lname' value='$lname'>";
echo '</div>';
echo '</div>';
echo '</div>';
echo '<br>';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '<div class="form-group">';
echo '<label>About Me</label>';
echo '<textarea class="form-control textarea">Oh so, your weak rhyme You doubt I will bother, reading into it</textarea>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="update ml-auto mr-auto">';
echo '<button type="submit" class="btn btn-primary btn-round">Update Profile</button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<footer class="footer footer-black  footer-white ">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<nav class="footer-nav">';
echo '<ul>';
echo '<li><a href="https://www.creative-tim.com" target="_blank">Creative Tim</a></li>';
echo '<li><a href="https://www.creative-tim.com/blog" target="_blank">Blog</a></li>';
echo '<li><a href="https://www.creative-tim.com/license" target="_blank">Licenses</a></li>';
echo '</ul>';
echo '</nav>';
echo '<div class="credits ml-auto">';
echo '<span class="copyright">';
echo '© <script>';
echo 'document.write(new Date().getFullYear())';
echo '</script>, made with <i class="fa fa-heart heart"></i> by Creative Tim';
echo '</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '</div>';
echo '</div>';
echo '</html>';
?>